name: POLYMARKET_TRIGGER_TRADE_HISTORY_SCHEDULE
pipeline_uuid: ingestion_trade_history
schedule_interval: null
schedule_type: api
status: active

variables:
  run_date: "{{ execution_date }}"

settings:
  sla: 120
